name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.5.0, v2.0.1, etc.

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.13

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false