name: Unit Tests

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version
          cache: 'pip'  # Enable pip caching

      - name: Install test dependencies
        run: pip install pytest pytest-cov pytest-timeout

      - name: Install project dependencies
        run: pip install -r requirements.txt

      - name: Run backend tests
        run: >
          pytest tests/backend/ --cov --cov-append --cov-branch \
            --cov-report=xml --junitxml=./junit.xml

      - name: Run utils tests
        run: >
          pytest tests/utils/ --cov --cov-append --cov-branch \
            --cov-report=xml --junitxml=./junit.xml

      - name: Run control test
        run: >
          pytest tests/test_control.py --cov --cov-append --cov-branch \
            --cov-report=xml --junitxml=./junit.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./junit.xml,!./cache
          flags: python3.10
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
